### PR TITLE
CMake Install for SDK and Toolchain and Github Action Build

### PR DESCRIPTION
**Pull request by vondraussen**
This will add some CMake steps to download and extract the toolchain and the zigbee SDK.
Also Github will build this project and makes switch and light binaries available for download.

### CODE REVIEW

**Comment by vondraussen** [comment]
@doctor64 Is it possible for you to test the generated binaries from the github action?

**Comment by doctor64** [comment]
Thank you very much for your contribution!
I'm not really github actions and cmake expert, so I have few questions:
1. As I understand, this will use windows based build system, correct?
2. Will this PR broke existing linux build? (I think yes)
3. Can you rework it to be cross-platform? Sorry, as I said i not expert in this.

I will check generated binaries from your repo ASAP, may be tomorrow

**Comment by vondraussen** [comment]
Yes, it is Windows only. The only reason for that is the fact, that I was only able to find the windows compiler. If you can point me to the Linux toolchain, I will implement this as well.

**Comment by doctor64** [comment]
See docs/linux_build.md

**Comment by vondraussen** [comment]
Sorry I didn't see that. Will work on that.

**Pull request closed without merging**
